name: aebridge
description: Enable interoperability and facilitate the transfer of data and assets between the two blockchains.
publish_to: "none"

version: 1.0.6+75

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  archethic_dapp_framework_flutter: ^1.2.7
  #archethic_dapp_framework_flutter:
  #  git:
  #    url: https://github.com/archethic-foundation/archethic-dapp-framework-flutter.git
  #    ref: main
  #archethic_dapp_framework_flutter:
  #  path: ../archethic-dapp-framework-flutter

  # A client dart library to interact with Archethic Wallet RPC API.
  archethic_wallet_client: ^2.0.4
  #archethic_wallet_client:
  #  git:
  #    url: https://github.com/archethic-foundation/archethic-wallet-client-dart.git
  #    ref: dev

  # Implementations of SHA, MD5, and HMAC cryptographic functions
  crypto: ^3.0.3

  # The decimal package allows you to deal with decimal numbers without losing precision
  decimal: ^3.0.2

  flutter:
    sdk: flutter

  # Add beautiful animated effects & builders in Flutter, via an easy, customizable, unified API.
  flutter_animate: ^4.5.0

  flutter_localizations:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.5.1

  # An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable Vector Graphics 1.1 files.
  flutter_svg: ^2.0.10+1

  # Annotations for freezed
  freezed_annotation: ^2.4.1

  # A declarative router for Flutter based on Navigation 2 supporting deep linking, data-driven routes and more
  go_router: ^13.2.0

  # Hive is a lightweight and blazing fast key-value database written in pure Dart
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # A composable, multi-platform, Future-based API for HTTP requests
  http: ^1.2.1

  # Contains code to deal with internationalized/localized messages, date and number formatting and parsing, bi-directional text, and other internationalization issues.
  intl: ^0.19.0

  # Defines the annotations used by json_serializable to create code for JSON serialization and deserialization.
  json_annotation: ^4.8.1

  # Flutter plugin for getting commonly used locations on host platform file systems, such as the temp and app data directories.
  path_provider: ^2.1.2

  # A package exposing annotations for riverpod_generator
  riverpod_annotation: ^2.3.5

  # Flutter plugin for launching a URL. Supports web, phone, SMS, and email schemes
  url_launcher: ^6.2.5

  # Flutter package that allows setting the web app URL strategy with a single line of code.
  url_strategy: ^0.2.0

  # Dart library to connect to Ethereum clients. Send transactions and interact with smart contracts!
  webthree: ^2.7.4
  #1webthree:
  #  git:
  #    url: https://github.com/redDwarf03/webthree.git
  #    ref: master

dev_dependencies:
  # A build system for Dart code generation and modular compilation.
  build_runner: ^2.4.8
  # A tool to help you find missing, under-promoted, over-promoted, and unused dependencies.
  # Code generation for immutable classes that has a simple syntax/API without compromising on the features.
  freezed: ^2.4.7
  # Extension for Hive. Automatically generates TypeAdapters to store any class.
  hive_generator: ^2.0.1
  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.7.1
  # A code generator for Riverpod. This both simplifies the syntax empowers it, such as allowing stateful hot-reload.
  riverpod_generator: ^2.4.0
  # A full featured library for writing and running Dart tests across platforms.
  test: ^1.25.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/bc-logos/
    - assets/images/token-icons/
    - lib/domain/repositories/blockchains_list.json
    - lib/domain/repositories/tokens_list_per_bridge.json
    - lib/domain/repositories/pools.json
    - contracts/evm/artifacts/contracts/Pool/PoolBase.sol/PoolBase.json
    - contracts/evm/artifacts/contracts/HTLC/HTLCBase.sol/HTLCBase.json
    - contracts/evm/artifacts/contracts/HTLC/HTLC_ERC.sol/HTLC_ERC.json
    - contracts/evm/artifacts/contracts/HTLC/HTLC_ETH.sol/HTLC_ETH.json
    - contracts/evm/artifacts/interfaces/IPool.sol/IPool.json
    - contracts/evm/artifacts/@openzeppelin/contracts/token/ERC20/ERC20.sol/ERC20.json
    - contracts/evm/artifacts/@openzeppelin/contracts/token/ERC20/IERC20.sol/IERC20.json
    - contracts/evm/artifacts/contracts/HTLC/SignedHTLC_ERC.sol/SignedHTLC_ERC.json
    - contracts/evm/artifacts/contracts/HTLC/SignedHTLC_ETH.sol/SignedHTLC_ETH.json
    - contracts/evm/artifacts/contracts/HTLC/ChargeableHTLC_ERC.sol/ChargeableHTLC_ERC.json
    - contracts/evm/artifacts/contracts/HTLC/ChargeableHTLC_ETH.sol/ChargeableHTLC_ETH.json

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
    - family: Iconsax
      fonts:
        - asset: assets/fonts/Iconsax.ttf
    - family: PPTelegraf
      fonts:
        - asset: assets/fonts/PPTelegraf-Ultralight.otf
          weight: 200
        - asset: assets/fonts/PPTelegraf-Light.otf
          weight: 300
        - asset: assets/fonts/PPTelegraf-Regular.otf
          weight: 400
        - asset: assets/fonts/PPTelegraf-Medium.otf
          weight: 500
        - asset: assets/fonts/PPTelegraf-Semibold.otf
          weight: 600
        - asset: assets/fonts/PPTelegraf-Bold.otf
          weight: 700
        - asset: assets/fonts/PPTelegraf-Ultrabold.otf
          weight: 800
        - asset: assets/fonts/PPTelegraf-Black.otf
          weight: 900
