name: aebridge
description: Enable interoperability and facilitate the transfer of data and assets between the two blockchains.
publish_to: "none"

version: 0.0.9+17

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  # A client dart library to interact with Archethic Wallet RPC API.
  archethic_wallet_client: ^1.0.0
  #archethic_wallet_client:
  #  git:
  #    url: https://github.com/archethic-foundation/archethic-wallet-client-dart.git
  #    ref: dev

  # Centralized loading widget management
  busy: ^1.0.2

  # Implementations of SHA, MD5, and HMAC cryptographic functions
  crypto: ^3.0.3

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter

  # Add beautiful animated effects & builders in Flutter, via an easy, customizable, unified API.
  flutter_animate: ^4.2.0+1

  flutter_localizations:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.3.6

  # An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable Vector Graphics 1.1 files.
  flutter_svg: ^2.0.9

  # Annotations for freezed
  freezed_annotation: ^2.4.1

  # Simple direct Service Locator that allows to decouple the interface from a concrete implementation and to access the concrete implementation from everywhere in your App
  get_it: ^7.6.0

  # A declarative router for Flutter based on Navigation 2 supporting deep linking, data-driven routes and more
  go_router: ^10.0.0

  # Gradient borders for inputs and containers. Borders package integrated with a basic flutter widgets as a container and input decorations. Easy in use, platform independent.
  gradient_borders: ^1.0.0

  # Hive is a lightweight and blazing fast key-value database written in pure Dart
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # A composable, multi-platform, Future-based API for HTTP requests
  http: ^1.0.0

  # Contains code to deal with internationalized/localized messages, date and number formatting and parsing, bi-directional text, and other internationalization issues.
  intl: any

  # Defines the annotations used by json_serializable to create code for JSON serialization and deserialization.
  json_annotation: ^4.8.1

  # Loading animation or loading spiner or loader. It's used to show loading animation when the app is in loading state or something is processing for uncertain time.
  loading_animation_widget: ^1.2.0+4

  # Flutter plugin for querying information about the application package, such as CFBundleVersion on iOS or versionCode on Android
  package_info_plus: ^4.1.0

  # Flutter plugin for getting commonly used locations on host platform file systems, such as the temp and app data directories.
  path_provider: ^2.1.0

  # A package exposing annotations for riverpod_generator
  riverpod_annotation: ^2.1.1

  # Bar indicator made of a series of selected and unselected steps
  step_progress_indicator: ^1.0.2

  # Flutter plugin for launching a URL. Supports web, phone, SMS, and email schemes
  url_launcher: ^6.1.12

  # Wave animation
  wave: ^0.2.2

  # Dart library to connect to Ethereum clients. Send transactions and interact with smart contracts!
  #webthree: ^2.5.11
  webthree:
    git:
      url: https://github.com/redDwarf03/webthree.git
      ref: add-wallets-support

dev_dependencies:
  # A build system for Dart code generation and modular compilation.
  build_runner: ^2.3.3
  # A tool to help you find missing, under-promoted, over-promoted, and unused dependencies.
  dependency_validator: ^3.0.0
  # Code generation for immutable classes that has a simple syntax/API without compromising on the features.
  freezed: ^2.4.0
  # Extension for Hive. Automatically generates TypeAdapters to store any class.
  hive_generator: ^2.0.0
  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.7.1
  # A code generator for Riverpod. This both simplifies the syntax empowers it, such as allowing stateful hot-reload.
  riverpod_generator: ^2.2.4
  # A full featured library for writing and running Dart tests across platforms.
  test: ^1.24.5

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/bc-logos/
    - lib/domain/repositories/blockchains_list.json
    - lib/domain/repositories/tokens_list_per_bridge.json
    - contracts/evm/artifacts/contracts/Pool/PoolBase.sol/PoolBase.json
    - contracts/evm/artifacts/contracts/HTLC/HTLCBase.sol/HTLCBase.json
    - contracts/evm/artifacts/contracts/HTLC/HTLC_ERC.sol/HTLC_ERC.json
    - contracts/evm/artifacts/contracts/HTLC/HTLC_ETH.sol/HTLC_ETH.json
    - contracts/evm/artifacts/interfaces/IPool.sol/IPool.json
    - contracts/evm/artifacts/@openzeppelin/contracts/token/ERC20/ERC20.sol/ERC20.json
    - contracts/evm/artifacts/@openzeppelin/contracts/token/ERC20/IERC20.sol/IERC20.json
    - contracts/evm/artifacts/contracts/HTLC/SignedHTLC_ERC.sol/SignedHTLC_ERC.json
    - contracts/evm/artifacts/contracts/HTLC/SignedHTLC_ETH.sol/SignedHTLC_ETH.json
    - contracts/evm/artifacts/contracts/HTLC/ChargeableHTLC_ERC.sol/ChargeableHTLC_ERC.json
    - contracts/evm/artifacts/contracts/HTLC/ChargeableHTLC_ETH.sol/ChargeableHTLC_ETH.json

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
    - family: Iconsax
      fonts:
        - asset: assets/fonts/Iconsax.ttf
    - family: PPTelegraf
      fonts:
        - asset: assets/fonts/PPTelegraf-Ultralight.otf
          weight: 200
        - asset: assets/fonts/PPTelegraf-Light.otf
          weight: 300
        - asset: assets/fonts/PPTelegraf-Regular.otf
          weight: 400
        - asset: assets/fonts/PPTelegraf-Medium.otf
          weight: 500
        - asset: assets/fonts/PPTelegraf-Semibold.otf
          weight: 600
        - asset: assets/fonts/PPTelegraf-Bold.otf
          weight: 700
        - asset: assets/fonts/PPTelegraf-Ultrabold.otf
          weight: 800
        - asset: assets/fonts/PPTelegraf-Black.otf
          weight: 900
