on:
  push:
    branches:
      - testnet

jobs:
  deploy_to_aeweb:
    runs-on: ubuntu-latest
    name: A job to deploy file to AEweb
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check files
        run: |
          ls -R

      - name: Clone and copy bridge-contracts repository
        run: |
          rm contracts
          git clone https://github.com/archethic-foundation/bridge-contracts.git
          mkdir contracts
          cp -r bridge-contracts/* contracts/
        
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Build web app
        run: flutter build web --web-renderer canvaskit --release

      - name: Check files
        run: |
          ls -R

      - name: Deploy to AEweb
        id: deploy
        uses: archethic-foundation/aeweb-github-action@v1.8.1
        with:
          seed: ${{ secrets.ARCH_BASE_SEED }}
          endpoint: "https://testnet.archethic.net"
          path: "build/web"
          keychainFundingService: "archethic-wallet-ARCHETHIC.NET"
          keychainWebsiteService: "aeweb-BRIDGE"
